[#66] 장바구니 페이지 UI 및 기능
woowa-techcamp-2021/store-4 pull request #109
Opened 2021-08-23 02:41 UTC by momongss

### 관련이슈
- #66 

### 실제 소요시간
- 24h

### 체크리스트
- [ ] `base branch`를 확인했나요?

### 설명
- cartStore에서 global 상태를 로컬 스토리지로 관리합니다.
- addProductToCart 같은 함수를 cartStore 에 구현했습니다.

생각보다 작업이 너무 늦어져서 죄송합니다. ㅠㅠ
아직 테스트 코드는 작성하지 못했는데 일단 풀리퀘만 올려두겠습니다.

2021-08-23 05:45 UTC, sanginchun commented on client/src/components/Cart/Cart.tsx
> +import { useState } from 'react';
위쪽으로 옮기면 좋을 것 같아요!

2021-08-23 05:48 UTC, Choi-Jinwoo reviewed
수고하셨습니다 ㅎㅎ 
컴포넌트 분리가 잘 되어 있네요!

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/components/Cart/Cart.tsx
> +        <MoveShopPage>{`<`} 쇼핑 계속하기</MoveShopPage>
```suggestion
<MoveShopPage>{`< 쇼핑 계속하기`}</MoveShopPage>
```

처럼 모두 템플릿 리터럴 안에 넣는건 어떨까요?

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/components/Cart/Cart.tsx
> +      {modalCartItem ? <Modal onCloseModalClick={onCloseModalClick} /> : null}
`null`을 반환하는 삼항 연산자보단 `&&`를 사용하면 어떨 까요?

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/components/Cart/CartTable/CartTable.tsx
> +        <DeliveryFee>기본 배송비 {toKoreanMoneyFormat(2500)} (택배-선결제)</DeliveryFee>
배송비는 빼기로 했었어요 ㅎㅎ

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/components/Cart/PriceTotalWrapper/PriceTotalWrapper.tsx
> +          총 <TextCount>2</TextCount> 개의 상품금액
`2`개의 상품 금액에서 2는 아직 Mock인가요?

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/stores/cartStore.ts
> +    this.modalCartItemId = 0;
`constructor`에서 실행하면 라우터가 바뀌었을때 실행이 안될 것 같은데 `init`이나 `fetch`와 같이 분리하여`useEffect`에서 해당 메소드를 호출하는 식으로 하는건 어떨 까요?

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/stores/cartStore.ts
> +    } as CartItem);
뒤에 `as CartItem`이 붙는 이유가 있을까요?

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/stores/cartStore.ts
> +  addProductToCart(productId: number, title: string, imgSrc: string, count: number, price: number) {
여러 상태의 변경이 있어 보여 `@action` 데코레이터를 통해 한번에 처리할 수 있도록 하는 건 어떨까요 ?

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/stores/cartStore.ts
> +    }
`number` 타입으로 온 데이터라 따로 검증이 필요할까 싶은데 `count <= 0`쪽 검증만 하고 그 외는 외부에서 하는게 맞을 듯 하네요!

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/stores/cartStore.ts
> +    this.cartItemList = [...this.cartItemList];
음 같은 배열을 `set`해주는 이유가 있을까요? 불필요한 렌더링만 일어나지 않을까 싶습니당 !

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/stores/cartStore.ts
> +    localStorage.setItem('cart', JSON.stringify(cartItemList));
`'cart'`같은 key값은 따로 상수로 분리하는 건 어떨까요?

2021-08-23 05:48 UTC, Choi-Jinwoo commented on client/src/utils/moneyFormater.ts
> +export const toKoreanMoneyFormatPure = (amount: number): string => {
`1,000`과 같은 경우는 그냥 숫자 포맷이라 `Money`라는 단어가 필요없을것 같아요 :)

2021-08-23 05:50 UTC, momongss commented on client/src/components/Cart/PriceTotalWrapper/PriceTotalWrapper.tsx
> +          총 <TextCount>2</TextCount> 개의 상품금액
아.. 저 부분도 스토어에서 상품리스트 수로 받아와서 했어야했는데 빠뜨렸네요. 수정하겠습니다.

2021-08-23 05:52 UTC, sanginchun commented on client/src/components/Cart/Cart.tsx
> +import { observer } from 'mobx-react-lite';
조금 찾아봤는데 `mobx-react`하고 `mobx-react-lite` 차이를 잘 모르겠네요. 일단은 통일성 있게 `mobx-react` 한 가지만 사용하는게 어떨까 싶습니다 🙂  (참고)[https://mobx.js.org/react-integration.html]

2021-08-23 05:53 UTC, momongss commented on client/src/components/Cart/Cart.tsx
> +import { observer } from 'mobx-react-lite';
네 하나로 통일하는게 좋겠네요. 수정하겠습니다.

2021-08-23 05:53 UTC, momongss commented on client/src/utils/moneyFormater.ts
> +export const toKoreanMoneyFormatPure = (amount: number): string => {
아 그렇겠네요. 네이밍으로 고민했었는데 `Money`를 빼면 되겠군요.

2021-08-23 05:54 UTC, momongss commented on client/src/stores/cartStore.ts
> +    localStorage.setItem('cart', JSON.stringify(cartItemList));
네 그렇겠네요. 수정하겠습니다.

2021-08-23 05:55 UTC, sanginchun commented on client/src/components/Cart/CartHeader/CartHeader.tsx
> +    돋움, sans-serif;
합치는 작업하면서 폰트도 통일을 한 번 해야겠네요.. 🥲

2021-08-23 06:01 UTC, sanginchun commented on client/src/components/Cart/CartHeader/CartHeader.tsx
> +        </Progress>
텍스트를 배열에 상수로 관리하고, 현재 단계를 상위 컴포넌트로부터 props로 받으면 for문으로 좀 더 간결하게 작성할 수 있을 것 같아요! 추가로 나중에 주문서작성이나 주문완료를 작업할 때도 좀 더 수월해지지 않을까 생각합니다. 🙂

2021-08-23 06:02 UTC, sanginchun commented on client/src/components/Cart/CartTable/CartItem/CartItem.tsx
> +
이렇게도 사용할 수 있군요 👍

2021-08-23 06:14 UTC, momongss commented on client/src/stores/cartStore.ts
> +    this.cartItemList = [...this.cartItemList];
어.. 일단 일부러 리렌더링을 발생시키려는 의도였습니다. 방금 논의한 대로 전체를 바꾸지 말고 프로퍼티만 변경해서 리렌더링 시키는 걸 시도해봤는데 cartItemList 을 배열로 작성해서 그게 조금 어렵네요.. 일단 그대로 두겠습니다.

2021-08-23 06:15 UTC, momongss commented on client/src/components/Cart/Cart.tsx
> +        <MoveShopPage>{`<`} 쇼핑 계속하기</MoveShopPage>
좋네요. ㅎㅎ

2021-08-23 06:16 UTC, sanginchun commented on client/src/stores/cartStore.ts
> +    const cartItemList = JSON.parse(localStorage.getItem('cart') as string);
as string으로 처리하는 것보다는 에러 처리를 따로 해주는게 좋을 것 같은데 어떠신가요?

2021-08-23 06:16 UTC, momongss commented on client/src/components/Cart/Cart.tsx
> +      {modalCartItem ? <Modal onCloseModalClick={onCloseModalClick} /> : null}
좋습니다.!!

2021-08-23 06:19 UTC, sanginchun commented on client/src/stores/cartStore.ts
> +
getter를 사용하면 좋을 것 같습니다.

2021-08-23 06:28 UTC, momongss commented on client/src/stores/cartStore.ts
> +    this.modalCartItemId = 0;
직접 논의해서 해결했습니다.

2021-08-23 06:30 UTC, momongss commented on client/src/stores/cartStore.ts
> +    } as CartItem);
`isSelected`프로퍼티를 빠뜨렸었네요. `isSelected` 추가하고 `as CartItem` 은 뺐습니다.

2021-08-23 06:31 UTC, momongss commented on client/src/stores/cartStore.ts
> +  addProductToCart(productId: number, title: string, imgSrc: string, count: number, price: number) {
아 새로운 걸 알았네요! 감사합니다.

2021-08-23 06:32 UTC, sanginchun commented on client/src/stores/cartStore.ts
> +  setCartItemList(cartItemList: CartItem[]) {
요거는 로컬 스토리지에 데이터를 set하는 함수니까 네이밍에 명시가 되면 좀 더 읽기 수월할 거 같습니다 :)

2021-08-23 06:35 UTC, sanginchun commented on client/src/stores/cartStore.ts
> +  }
find 함수를 사용하면 좋을 것 같습니다. 또 한가지는 이 함수를 호출하는 입장에서 이미 id를 가지고 있다면 categoryStore.cartItemList에서 직접 찾아도 되는 거 아닐까 생각이 드네요. 🤔

2021-08-23 06:40 UTC, momongss commented on client/src/components/Cart/CartHeader/CartHeader.tsx
> +    돋움, sans-serif;
아.. 그렇겠네요.

2021-08-23 06:40 UTC, momongss commented on client/src/components/Cart/CartTable/CartTable.tsx
> +        <DeliveryFee>기본 배송비 {toKoreanMoneyFormat(2500)} (택배-선결제)</DeliveryFee>
넵..!!

2021-08-23 06:54 UTC, sanginchun commented on client/src/stores/cartStore.ts
> +  }
위에서 count를 한번 검증하는데 아래에서 또 해주는 이유가 있을까요?

2021-08-23 06:55 UTC, juyoungpark718 requested changes
에러 처리에 대해서 리뷰한 곳은 꼭 체크해주셔야할 것 같습니다 !
그 외에는 크게 크리티컬한 부분들은 아니여서 한번 봐주시면 감사하겠습니다 :)
장바구니 정말 어려워보이는데 구현하느라 정말 고생 많으셨습니다 :) 👍 👍

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/components/Cart/CartButtons/CartButtons.tsx
> +const ProductButtonList = styled(ResetButton)``;
상속해서 사용하는거 너무 좋네요 :) 👍

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/components/Cart/CartTable/CartTable.tsx
> +    <CartTableWrapper>
저희 최상위(?) Wrapper는 Container로 통일하기로 하지 않았나요 ?!

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/components/Cart/Modal/CountOption/CountOption.tsx
> +`;
제가 보기엔 CountUpButton, CountDownButton이 똑같아 보이는데,
```suggestion
const CountButton = styled.button`
  width: 23px;
  height: 17px;
  font-size: ${(props) => props.theme.fontSize.tiny};
  color: ${(props) => props.theme.color.grey4};
  background-color: ${(props) => props.theme.color.white1};
  border: 1px solid ${(props) => props.theme.color.grey3};
  background: none;
  color: inherit;
  border: none;
  padding: 0;
  font: inherit;
  cursor: pointer;
  outline: inherit;
`;

const CountUpButton = styled(CountButton)``;
const CountDownButton = styled(CountButton)``;
```

이런식으로 작성해도 좋을 것 같습니다. 중복 되는 부분은 CountButton으로 다 올리고, Up, Down 컴포넌트로 나누는 것도 중복을 더 줄일 수 있을 거같은데 어떻게 생각하시나요 ? :)

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/components/Cart/Modal/CountOption/CountOption.tsx
> +  };
props.setProductCount로 계속 사용하시는데, 

```
cosnt { productCount, setProductCount } = props; 
```

로  풀어서 사용하면 좀 더 편할 것 같은데 혹시 제가 발견  못한 이유가 있을까요?  ㅎㅎ

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/components/Cart/Modal/Modal.tsx
> +const Modal = (props: Props): JSX.Element => {
공용 컴포넌트 모달이 아니고 Cart에서 사용하는 모달이면 이름을 좀 더 명확하게 지어도 더 좋을 것 같은데 어떻게 생각하세요 ? :)

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/components/Cart/PriceTotalWrapper/PriceTotalWrapper.tsx
> +  }
filter, reduce와 같은 고차함수로 작성할 수도 있겠네요 ! :)
제 개인적인 취양인데 저는 filter, reduce가 좀 더 직관적이라고 생각이 드네요.. ㅎ

```suggestion
   const totalPrice = cartItemList
     .filter((cartItem) => cartItem.isSelected)
     .reduce((total, cartItem) => {
      total += cartItem.price * cartItem.count;
      return total;
    }, 0);
```

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/models/cartItem.ts
> +  }
model에서 count * price 값을 계산해줘도 좋을 것 같아요 :) product 모델을 한번 참고해보셔도 좋을 것 같습니다.

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/stores/cartStore.ts
> +    const cartItemList = JSON.parse(localStorage.getItem('cart') as string);
해당 부분에서 에러 처리가 필요한 것 같아요. localStorage에서 getItem이 없는 경우도 있고, 배열이 있다고 하더라도 안에 있는 값들이 CartItem인 처리가 필요한 것 같습니다.

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/stores/cartStore.ts
> +  }
```suggestion
  setCartItemSelectionAll(isSelected: boolean) {
    this.cartItemList = this.cartItemList.map((cartItem) => {
      cartItem.isSelected = isSelected;
      return cartItem;
    });
    this.setCartItemList(this.cartItemList);
  }
```

이런 식으로 고차함수도 활용해서 할 수 있을 것 같습니다 :)

2021-08-23 06:55 UTC, juyoungpark718 commented on client/src/components/Cart/PriceTotalWrapper/PriceTotalWrapper.tsx
> +  }
막상 해놓고 보니까 비슷하네요 ..? 그냥 넘어가셔도 될 것 같습니다 .. ㅎ

2021-08-23 06:56 UTC, sanginchun commented on client/src/stores/cartStore.ts
> +
아 제가 잘못 생각한것 같습니다 이 부분은.

함수가 아니라 cartStore.cartItemList로 접근하면 되지 않을까요? 🤔

2021-08-23 07:45 UTC, momongss commented on client/src/components/Cart/CartHeader/CartHeader.tsx
> +        </Progress>
넵. 말씀하신대로 수정했습니다. 현재 단계를 상위 컴포넌트에서 props 로 받으니 더 좋아보이네요.

2021-08-23 07:47 UTC, momongss commented on client/src/stores/cartStore.ts
> +  setCartItemList(cartItemList: CartItem[]) {
넵 수정했습니다.

2021-08-23 07:53 UTC, momongss commented on client/src/stores/cartStore.ts
> +  }
넵 반영했습니다.

2021-08-23 07:55 UTC, momongss commented on client/src/stores/cartStore.ts
> +  }
그러게요.. 지웠어야 했는데 빠뜨린 것 같습니다.

2021-08-23 08:04 UTC, momongss commented on client/src/components/Cart/Modal/CountOption/CountOption.tsx
> +`;
너무 좋네요. 반영했습니다!

2021-08-23 08:06 UTC, momongss commented on client/src/components/Cart/Modal/CountOption/CountOption.tsx
> +  };
이 컴포넌트를 작성하기 시작할 때 내부에 `count` 라는 변수가 따로 있었어서 `props` 에서 넘어온 `productCount` 와 구분하고 싶어서 이렇게 작성했는데 이제보니 `count` 라는 변수도 없어져서 말씀하신대로 바꾸는게 좋겠네요.

2021-08-23 08:29 UTC, momongss commented on client/src/stores/cartStore.ts
> +    const cartItemList = JSON.parse(localStorage.getItem('cart') as string);
넵. 이번 기회에 많이 배웠습니다. 수정했습니다. 감사합니다.

2021-08-23 08:31 UTC, momongss commented on client/src/components/Cart/Modal/Modal.tsx
> +const Modal = (props: Props): JSX.Element => {
아 그렇네요. `CartModal` 정도가 괜찮을 것 같습니다.

2021-08-23 08:32 UTC, momongss commented on client/src/components/Cart/CartTable/CartTable.tsx
> +    <CartTableWrapper>
앗.. 그렇군요..

2021-08-23 08:55 UTC, momongss commented on client/src/stores/cartStore.ts
> +    const cartItemList = JSON.parse(localStorage.getItem('cart') as string);
넵 아래 주영님이 달아주신 리뷰처리하며 같이 해줬습니다.

2021-08-23 08:56 UTC, momongss commented on client/src/models/cartItem.ts
> +  }
옵션 부분해주면서 같이 생각해보도록 하겠습니다.

2021-08-24 00:49 UTC, juyoungpark718 commented on client/src/components/Cart/CartModal/CountOption/CountOption.tsx
> +import { isNotNone } from '../../../../utils/typeGuard';
앗! lint warning

2021-08-24 00:49 UTC, juyoungpark718 commented on client/src/components/Cart/CartTable/TableHeader/TableHeader.tsx
> +import React, { useEffect, useState } from 'react';
lint warning!

2021-08-24 00:49 UTC, juyoungpark718 commented on client/src/components/Cart/helper.ts
> +};
요기 함수들 안에서 none인지 아닌지 처리해주는데, selectWithSelected가 none인 경우까지 받아서 처리하면, 이 함수들을 사용하는 애들에서 삼항연산자를 사용하지 않아도 될 것 같은데 어떻게 생각하세요?? :) 제가 미처 발견하지 못한 이유가 있을까요 ? 흠..

2021-08-24 07:57 UTC, momongss commented on client/src/components/Cart/CartTable/TableHeader/TableHeader.tsx
> +import React, { useEffect, useState } from 'react';
! 확인했습니다.

2021-08-24 08:00 UTC, momongss commented on client/src/components/Cart/helper.ts
> +};
인자 타입으로 `SelectWithSelected | undefined ` 를 주고 None 을 걸러내면 외부에서 삼항연산자를 안써줘도 되는군요! 미처 발견하지 못한 다른 이유는 없습니다! 반영했습니다.

2021-08-24 08:06 UTC, momongss commented on client/src/stores/cartStore.ts
> +    }
타입스크립트가 이런 점에서 장점이 있군요..
앞에 검증은 빼고 `count <= 0` 일 시 `count=1` 이 되도록 변경했습니다.

2021-08-24 08:14 UTC, juyoungpark718 approved these changes
고생하셨습니다 !! :) 👍 👍  코멘트 한번만 확인해주세요 !

2021-08-24 08:14 UTC, juyoungpark718 commented on client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx
> +          ))}
요 과정을 변수로 따로 빼도 좋을 것 같네요 :)

2021-08-24 08:14 UTC, juyoungpark718 commented on client/src/components/Cart/Cart.tsx
> +import { useState } from 'react';
요거 두개 합쳐서 작성해도 되겠네요 :)

2021-08-24 08:18 UTC, Choi-Jinwoo approved these changes
수고하셨습니당 :)

2021-08-24 08:18 UTC, Choi-Jinwoo commented on client/src/components/Cart/CartModal/CountOption/CountOption.tsx
> +  const { productCount, setProductCount } = props;
`setProductCount`보다는 `increase`, `decrease`와 같이 `setState`를 사용하는 함수를 Props로 받는건 어떨까요?

`setState` 자체를 자식으로 넘기면 너무 많은 동작을 자식 컴포넌트에서 할 수 있을듯 해서요!

2021-08-24 08:24 UTC, sanginchun approved these changes
정말 고생 많으셨습니다 🥲

2021-08-24 08:24 UTC, sanginchun commented on client/src/stores/cartStore.ts
> +    const cartItemList = JSON.parse(localStorage.getItem('cart') as string);
이 부분은 아직 처리가 덜 된 것 같아요!

2021-08-24 08:24 UTC, sanginchun commented on client/src/components/Cart/Cart.tsx
> +import { useState } from 'react';
합쳐도 될 것 같습니다 ㅎㅎ

2021-08-24 08:51 UTC, merged